{% set name = "python-clingox" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/potassco/{{ name }}/archive/v{{ version }}.zip
  sha256: a368c43e25512bbe680dbac51e5a0bbc21e5d3f9fda8873c936c58d9432ee973

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - clingo >=5.5.0
    - python >=3.6

test:
  imports:
    - clingox
    - clingox.ast
    - clingox.backend
    - clingox.program
    - clingox.theory
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://potassco.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A support library for the clingo Python library.
  description: |
    The clingox library collects useful Python functions that can be used along
    with the clingo libary.
  doc_url: https://potassco.org/clingo
  dev_url: https://github.com/potassco/{{ name }}

extra:
  recipe-maintainers:
    - rkaminsk
